"""
Parse legacy (WinRegatta) HTML racing result files (1999–2011).

These files have a consistent table structure generated by the WinRegatta
scoring software. Each file represents a single race with embedded metadata
(wind direction/speed, course, distance, start time, etc.).
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field, asdict
from pathlib import Path

from bs4 import BeautifulSoup, Tag

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = PROJECT_ROOT / "scraper" / "parsed"


@dataclass
class LegacyRaceResult:
    """A single boat's result in a legacy race."""
    boat_name: str = ""
    sail_number: str = ""
    boat_class: str = ""
    rating: str = ""
    race_date: str = ""
    finish_time: str = ""
    penalty: str = ""
    elapsed_time: str = ""
    corrected_time: str = ""
    position: int | None = None
    points: float | None = None
    espn: str = ""
    series_points: float | None = None
    series_position: int | None = None
    status: str | None = None
    participant_type: str = "boat"


@dataclass
class LegacyRaceMetadata:
    """Metadata for a WinRegatta race."""
    event_name: str = ""
    race_class: str = ""
    course: str = ""
    race_date: str = ""
    distance: str = ""
    start_time: str = ""
    wind_direction: str = ""
    wind_speed: str = ""
    race_number: int | None = None
    race_total: int | None = None


@dataclass
class LegacyParsedPage:
    """A fully parsed legacy result page."""
    source_path: str = ""
    year: int | None = None
    title: str = ""
    metadata: LegacyRaceMetadata = field(default_factory=LegacyRaceMetadata)
    results: list[LegacyRaceResult] = field(default_factory=list)
    footer_event_name: str = ""
    footer_race_info: str = ""
    footer_date: str = ""
    errors: list[str] = field(default_factory=list)


def _clean_text(element: Tag | str) -> str:
    """Extract and clean text from a BeautifulSoup element or string."""
    if isinstance(element, str):
        text = element
    else:
        text = element.get_text()
    # Replace non-breaking spaces, strip whitespace
    return text.replace("\xa0", " ").strip()


def _extract_year_from_path(filepath: Path) -> int | None:
    """Extract year from the file path."""
    matches = re.findall(r"racing(\d{4})", str(filepath))
    if matches:
        return int(matches[-1])
    return None


def _safe_float(val: str) -> float | None:
    """Convert string to float, returning None for invalid values."""
    try:
        return float(val.strip())
    except (ValueError, AttributeError):
        return None


def _safe_int(val: str) -> int | None:
    """Convert string to int, returning None for invalid values."""
    try:
        return int(val.strip())
    except (ValueError, AttributeError):
        return None


def _parse_race_of(text: str) -> tuple[int | None, int | None]:
    """Parse 'N of M' race numbering text."""
    match = re.search(r"(\d+)\s+of\s+(\d+)", text.strip())
    if match:
        return int(match.group(1)), int(match.group(2))
    return None, None


def _detect_status(row_cells: list[str]) -> str | None:
    """Detect race status codes from cell values."""
    status_codes = {"DNC", "DNS", "DNF", "OCS", "DSQ", "RET", "DPI"}
    for cell in row_cells:
        upper = cell.strip().upper()
        if upper in status_codes:
            return upper
    return None


def _is_winregatta_page(soup: BeautifulSoup) -> bool:
    """Check if the HTML was generated by WinRegatta."""
    # Check meta generator tag
    meta = soup.find("meta", attrs={"name": re.compile(r"GENERATOR", re.I)})
    if meta and "winregatta" in str(meta.get("content", "")).lower():
        return True

    # Heuristic: WinRegatta pages have teal (#008080) metadata cells
    teal_cells = soup.find_all("td", bgcolor=re.compile(r"#008080", re.I))
    if len(teal_cells) >= 4:
        return True

    return False


def _extract_metadata(soup: BeautifulSoup) -> LegacyRaceMetadata:
    """Extract race metadata from the WinRegatta header table."""
    meta = LegacyRaceMetadata()

    # The metadata is stored in teal-labeled cells
    # Pattern: <td bgcolor="#008080"><strong><font>Label</font></strong></td>
    # followed by a <td> with the value
    teal_cells = soup.find_all("td", bgcolor=re.compile(r"#008080", re.I))
    for cell in teal_cells:
        label = _clean_text(cell).lower()
        # Get the next sibling td with the value
        next_td = cell.find_next_sibling("td")
        if not next_td:
            continue
        value = _clean_text(next_td)

        if "class" in label and "class" not in label.replace("class", "", 1):
            meta.race_class = value
        elif "course" in label:
            meta.course = value
        elif "race date" in label:
            meta.race_date = value
        elif "distance" in label:
            meta.distance = value
        elif "start time" in label:
            meta.start_time = value
        elif "wind direction" in label:
            meta.wind_direction = value
        elif "wind speed" in label:
            meta.wind_speed = value
        elif label == "race":
            race_num, race_total = _parse_race_of(value)
            meta.race_number = race_num
            meta.race_total = race_total

    # Extract event name from the title bar (blue #0000FF row)
    blue_cell = soup.find("td", bgcolor=re.compile(r"#0000FF", re.I))
    if blue_cell:
        meta.event_name = _clean_text(blue_cell)

    return meta


# Standard WinRegatta column order (0-indexed after colspan normalization)
WINREGATTA_COLUMNS = [
    "name", "sail_number", "type", "rating",
    "date", "finish_time", "penalty", "elapsed", "corrected",
    "position", "points", "espn", "series_points", "series_position",
]


def _find_header_row(soup: BeautifulSoup) -> Tag | None:
    """Find the red column header row."""
    # WinRegatta headers use red (#FF0000) background
    red_cells = soup.find_all("td", bgcolor=re.compile(r"#FF0000", re.I))
    if red_cells:
        return red_cells[0].find_parent("tr")
    return None


def _find_data_rows(soup: BeautifulSoup) -> list[Tag]:
    """Find all data rows (white background, not header/footer)."""
    rows = []
    # Data rows have bgcolor="#FFFFFF" on their cells
    for tr in soup.find_all("tr"):
        cells = tr.find_all("td")
        if not cells:
            continue

        # Skip header rows (blue/teal/red backgrounds)
        first_cell = cells[0]
        bg = str(first_cell.get("bgcolor", "")).upper()
        if bg in ("#0000FF", "#008080", "#FF0000", "#C0C0C0"):
            continue

        # Must have white bg and height="24" (data row marker)
        if bg == "#FFFFFF" or first_cell.get("height") == "24":
            # Skip rows with colspan (these are section headers or footers)
            if first_cell.get("colspan"):
                continue
            rows.append(tr)

    return rows


def _parse_data_row(tr: Tag) -> LegacyRaceResult | None:
    """Parse a single data row into a result."""
    cells = tr.find_all("td")
    if not cells:
        return None

    # Extract cell text values
    values = [_clean_text(cell) for cell in cells]

    # WinRegatta has a consistent 14-column layout
    # But some files have fewer columns; map by position
    result = LegacyRaceResult()

    if len(values) >= 4:
        result.boat_name = values[0]
        result.sail_number = values[1]
        result.boat_class = values[2]
        result.rating = values[3]

    if len(values) >= 9:
        result.race_date = values[4]
        result.finish_time = values[5]
        result.penalty = values[6]
        result.elapsed_time = values[7]
        result.corrected_time = values[8]

    if len(values) >= 11:
        result.position = _safe_int(values[9])
        result.points = _safe_float(values[10])

    if len(values) >= 12:
        result.espn = values[11]

    if len(values) >= 14:
        result.series_points = _safe_float(values[12])
        result.series_position = _safe_int(values[13])

    # Detect status codes
    result.status = _detect_status(values)

    # Skip empty/placeholder rows
    if not result.boat_name:
        return None

    return result


def _parse_footer(soup: BeautifulSoup) -> tuple[str, str, str]:
    """Extract footer row information (event name, race info, date)."""
    # Footer row has gray (#C0C0C0) background cells
    gray_cells = soup.find_all("td", bgcolor=re.compile(r"#C0C0C0", re.I))
    if not gray_cells:
        return "", "", ""

    # Usually 3 footer cells with colspan
    footer_texts = [_clean_text(cell) for cell in gray_cells]

    event_name = footer_texts[0] if len(footer_texts) > 0 else ""
    race_info = footer_texts[1] if len(footer_texts) > 1 else ""
    footer_date = footer_texts[2] if len(footer_texts) > 2 else ""

    return event_name, race_info, footer_date


def parse_legacy_file(filepath: Path) -> LegacyParsedPage:
    """Parse a single WinRegatta legacy HTML file."""
    page = LegacyParsedPage(
        source_path=str(filepath),
        year=_extract_year_from_path(filepath),
    )

    try:
        html = filepath.read_text(errors="replace")
    except Exception as e:
        page.errors.append(f"Could not read file: {e}")
        return page

    soup = BeautifulSoup(html, "lxml")

    # Extract title
    title_tag = soup.find("title")
    if title_tag:
        page.title = _clean_text(title_tag)

    # Check if this is actually a WinRegatta page
    if not _is_winregatta_page(soup):
        page.errors.append("Not a WinRegatta page")
        return page

    # Extract metadata
    page.metadata = _extract_metadata(soup)

    # Parse data rows
    data_rows = _find_data_rows(soup)
    for tr in data_rows:
        result = _parse_data_row(tr)
        if result:
            page.results.append(result)

    # Extract footer
    page.footer_event_name, page.footer_race_info, page.footer_date = _parse_footer(soup)

    return page


def parse_all_legacy(base_dir: Path | None = None) -> list[LegacyParsedPage]:
    """Parse all WinRegatta legacy HTML files."""
    if base_dir is None:
        base_dir = PROJECT_ROOT / "racing1999_2013"

    if not base_dir.exists():
        return []

    pages = []
    for filepath in sorted(base_dir.rglob("*.htm")):
        name_lower = filepath.name.lower()

        # Skip index pages, matrices, and non-result files
        if name_lower == "racing.htm":
            continue
        if "matrix" in name_lower:
            continue
        if "handicap" in name_lower and "system" in name_lower:
            continue
        if "instruction" in name_lower or "sailing_instruction" in name_lower:
            continue
        if name_lower.endswith("_si.htm"):
            continue

        # Skip Sailwave files — they're handled by parse_sailwave.py
        try:
            html = filepath.read_text(errors="replace")
            if "sailwave" in html.lower() or "summarytable" in html or "racetable" in html:
                continue
        except Exception:
            continue

        page = parse_legacy_file(filepath)
        if page.results and not page.errors:
            pages.append(page)

    return pages


def write_parsed_output(pages: list[LegacyParsedPage], output_dir: Path | None = None):
    """Write parsed output as JSONL."""
    if output_dir is None:
        output_dir = OUTPUT_DIR
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "legacy_parsed.jsonl"
    with open(output_file, "w") as f:
        for page in pages:
            f.write(json.dumps(asdict(page), default=str) + "\n")

    print(f"Parsed output written: {output_file} ({len(pages)} pages)")


def print_summary(pages: list[LegacyParsedPage]):
    """Print parsing summary."""
    from collections import Counter

    total_results = sum(len(p.results) for p in pages)
    by_year = Counter(p.year for p in pages)
    with_wind = sum(1 for p in pages if p.metadata.wind_direction.strip())
    errors = [e for p in pages for e in p.errors]

    print(f"\nParsed {len(pages)} legacy pages")
    print(f"  Total result rows: {total_results}")
    print(f"  Pages with wind data: {with_wind}")

    print("\nPages per year:")
    for year in sorted(by_year.keys()):
        print(f"  {year}: {by_year[year]}")

    if errors:
        print(f"\n  Errors: {len(errors)}")
        for e in errors[:10]:
            print(f"    {e}")


def main():
    pages = parse_all_legacy()
    write_parsed_output(pages)
    print_summary(pages)


if __name__ == "__main__":
    main()
